import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nextbar from "@/components/nxtnavbar";
import {Providers} from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
     
     
      <body ><Providers><Nextbar/>{children}</Providers></body>
    </html>
</>
  );
}
